<a href="https://colab.research.google.com/github/shahzaibedits23/AI-ML-DL-/blob/main/Assignment(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 Create a NumPy array from a Python list [1, 2, 3, 4, 5].

 Print the array and its type.

In [ ]:
import numpy as np

list = [1,2,3,4,5]
array = np.array(list)
print(array)

[1 2 3 4 5]


2 Use np.arange() to create a 1D array of numbers from 10 to 50.

 Print the shape and size of the array.

In [ ]:

array = np.arange(10,51)
print("Array:",array)
print("Shape:",array.shape)
print("Size:",array.size)

Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Shape: (41,)
Size: 41


3 Create a 2D NumPy array of shape (3, 4) filled with zeros using np.zeros().

 Convert all zeros into fives.

In [ ]:

array = np.zeros((3,4))
print(array)
array[:] = 5
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


4 Generate a 1D array of 15 random integers between 1 and 100 using np.random.randint().

 Find the maximum, minimum, and mean values.

In [ ]:
array = np.random.randint(1,101,15)
print(array)
print("Max:",array.max())
print("Min:",array.min())
print("Mean:",array.mean())

[ 46  39  97  20  43  99  82  17  42  12  85  65  47   5 100]
Max: 100
Min: 5
Mean: 53.266666666666666


5 Create a NumPy array of numbers from 1 to 20.

 Extract only the even numbers using slicing or boolean indexing.

 Reverse the array using slicing.

In [ ]:
array = np.arange(1,21)
print("Array",array)
print("Even Numbers:",array[array%2==0])
print("Reversed Array:",array[::-1])

Array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even Numbers [ 2  4  6  8 10 12 14 16 18 20]
Reversed Array [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


6 Create a NumPy array [10, 20, 30, 40, 50].  Print the first element

 Print the last element

In [ ]:
array = np.array([10,20,30,40,50])
print("First Element:",array[0])
print("Second Element:",array[-1])

First Element: 10
Second Element: 50


7 Make a 2D array of shape (4, 4) with numbers from 1 to 16.

 Extract the first two rows and last two columns.

 Replace the diagonal elements with 0.

In [ ]:
import numpy as np
array = np.array([[2,3,4,5],[4,3,2,6],[7,8,9,6],[4,2,5,1]])
print(array)
print("First two rows and last two columns:")
print(array[:2,2:])
np.fill_diagonal(array,0)
print("Diahonals replaced with Zero:")
print(array)

[[2 3 4 5]
 [4 3 2 6]
 [7 8 9 6]
 [4 2 5 1]]
First two rows and last two columns:
[[4 5]
 [2 6]]
Diahonals replaced with Zero:
[[0 3 4 5]
 [4 0 2 6]
 [7 8 0 6]
 [4 2 5 0]]


8 Create an array of 25 random integers between 1 and 100.

 Sort the array using np.sort().

In [ ]:
import numpy as np
array = np.random.randint(1,101,25)
print(array)
print("Sorted Array:")
print(np.sort(array))

[ 24 100  71  99  31  66  20  83  44  59  88  16  62   1  39   4  10  29
  27  46  20  85  79  69  41]
Sorted Array:
[  1   4  10  16  20  20  24  27  29  31  39  41  44  46  59  62  66  69
  71  79  83  85  88  99 100]


9 Create a 1D array of numbers from 1 to 10 and find:

 Maximum (np.max())

 Minimum (np.min())

 Sum (np.sum())

In [ ]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Maximum:", array.max())
print("Minimum:", array.min())
print("Sum:", array.sum())

Maximum: 10
Minimum: 1
Sum: 55


10 Reshape a 1D array of 36 elements into a 2D array of shape (6, 6).

 Find the sum of each row and each column using np.sum() with axis.

In [ ]:
import numpy as np
array = np.arange(36).reshape(6,6)
print(array)
print("Sum of each row:",np.sum(array,axis=1))
print("Sum of each column:",np.sum(array,axis=0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Sum of each row: [ 15  51  87 123 159 195]
Sum of each column: [ 90  96 102 108 114 120]
